:of-what: {of-sett-serv}
:version: {sett-serv-log-req}

= Журнал работы {of-sett-serv}

Журнал работы модуля в локальной файловой системе располагается в каталоге `/var/log/docsvision\settingsservice` для Linux и `C:\ProgramData\Docsvision\Logs\SettingsService` для Windows.

:module-service: {of-sett-serv}
include::6.1@webclient:admin:partial$excerpts.adoc[tags=no-rights]

include::GBL-3610@engineer:ROOT:partial$excerpts.adoc[tags=nlog-json]

[subs="specialchars,attributes,quotes"]
Журналирование с использованием NLog по умолчанию работает, когда в конфигурационном файле {config-ss} указаны настройки NLog. Если настройки в конфигурационном файле не указаны, журналирование будет работать по прежнему принципу.

Пути к журналам, уровень и режим журналирования настраиваются в конфигурационном файле по адресу {config-ss}:

[source,json]
----
{
  "NLog": {
    "targets": {
      "logFile": { <.>
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/settingsservice/settingsservice{event-properties:item=Tenant} PID ${processId} ${shortdate}.log", <.>
        "layout": "[${longdate}][${level}][${callsite}] ${message} ${exception:format=tostring,Data}"
        "logConsole": { "type": "Console" } <.>
      },
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn", <.>
        "writeTo": "logFile"
      }
    ]
  }
}
----
<.> `logFile` -- настройки для режима вывода журнала в файл.
<.> В `fileName` можно настроить путь для сохранения журнала работы. Поддерживаются https://github.com/nlog/NLog/wiki/File-target[допустимые для NLog переменные].
<.> `logConsole` -- настройки для режима вывода журнала в stdout/stderr процесса, например _journald_ в терминале Linux. Формат -- тот же JSON, что и для файла.
<.> Измените значение параметров `minLevel` и `maxLevel`, например, на `trace`, чтобы включить протоколирование всех типов событий. +
Допустимые уровни протоколирования приведены https://github.com/nlog/NLog/wiki/Configuration-file#log-levels[на странице NLog в GitHub]. +
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.

include::GBL-3610@engineer:ROOT:partial$modes-archivation-redefine.adoc[]